online_Book/app/cart/urls.py
from django.urls import path

from .views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    path("add", CartAddView.as_view(), name="add"),  # 购物车记录添加
    path("", CartInfoView.as_view(), name="show"),  # 购物车页面显示
    path("update", CartUpdateView.as_view(), name="update"),  # 购物车记录更新
    path("delete", CartDeleteView.as_view(), name='delete'),    # 购物车删除记录
]

online_Book/app/goods/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import IndexView, DetailView, ListView

urlpatterns = [
    # path('index/', IndexView.as_view(), name='index'),  # 首页
    url(r'^index/$', IndexView.as_view(), name='index'),  # 首页
    # path("goods/<goods_id>d+", DetailView.as_view(), name='detail'),  # 详情页
    # url(r'^goods/(?P<goods_id>\\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    re_path(r'goods/(?P<goods_id>\d+)', DetailView.as_view(), name='detail'),  # 详情页

    # path("goods/<goods_id>", DetailView.as_view(), name='detail'),
    # re_path('page=(?P<goods_id>\d+)&key=(?P<key>\w+)', DetailView.as_view(), name="detail"),

    # url(r'^list/(?P<type_id>\\d+)/(?P<page>\\d+)$', ListView.as_view(), name='list'),  # 列表页
    re_path(r'list/(?P<type_id>\d+)/(?P<page>\d+)', ListView.as_view(), name='list'),  # 列表页
    # d+:匹配一个种类的id

    # re_path(r'index/(\d+)/',views.index),
]

online_Book/app/order/urls.py
from .views import OrderPlaceView, OrderCommitView, CommentView, OrderPayView, CheckPayView
from django.urls import path, re_path

urlpatterns = [
    path("place", OrderPlaceView.as_view(), name="place"),  # 提交订单页面显示
    path('commit', OrderCommitView.as_view(), name='commit'),  # 订单提交
    path('pay', OrderPayView.as_view(), name='pay'),  # 订单支付
    path('check', CheckPayView.as_view(), name='check'),  # 订单校对
    #    re_path(r'comment/(?P<order_id>.+)', CommentView.as_view(), name='comment'),  # 订单评论
]

online_Book/app/user/urls.py
from django.urls import path,re_path
from django.contrib.auth.decorators import login_required
from . import views
from .views \
    import RegisterView, ActiveView, LoginView, \
    UserInfoView, UserOrderView, AddressView, LoginOutView

urlpatterns = [  # 指明路径，调用的页面，还有名称
    # path("register", views.register, name="register"),  # 注册
    # path("register_handle", views.register_handle, name='register_handle'),  # 注册处理
    path("register", RegisterView.as_view(), name="register"),  # 注册-类视图注册
    # register是从父类默认继承的方法
    path("active/<token>", ActiveView.as_view(), name="active"),  # 用户激活
    # 在Django2中直接采用 path("active/<token>"方式将后面的字符直接提取并存储在token中
    path("login", LoginView.as_view(), name="login"),  # 登录
    path("logout", LoginOutView.as_view(), name="logout"),  # 登出
    # 使用了utils里用Mixin包装了一下的loginrequired之后便可以简化一下
    # path("", login_required(UserInfoView.as_view()), name="user"),  # 用户信息
    #
    # path("order", login_required(UserOrderView.as_view()), name="order"),  # 订单信息
    #
    # path("address", login_required(AddressView.as_view()), name="address"),  # 地址信息

    path("", UserInfoView.as_view(), name="user"),  # 用户中心-用户信息页

    # path("order", UserOrderView.as_view(), name="order"),  # 用户中心-订单信息页
    re_path(r'order/(?P<page>\d+)', UserOrderView.as_view(), name='order'),  # 用户中-订单信息页

    path("address", AddressView.as_view(), name="address"),  # 用户中心-地址信息页
]

online_Book/online_Book/urls.py
# from django.urls import path, include
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search', include('haystack.urls')),  # 搜索界面
    path('user/', include(('user.urls', 'user'), namespace='user')),    #用户模块
    path('order/', include(('order.urls', 'order'), namespace='order')),  #订单模块
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),   #购物模块
    path('', include(('goods.urls', 'goods'), namespace='goods')),  # 书籍商品模块
]
# path('common/', include('common.urls', namespace='common')),  # 通用模块
# path('', include('app.common.urls')),
# path('user/', include('app.user.urls')),
# path('order/', include('app.order.urls')),
# path('cart/', include('app.cart.urls')),
# path('goods', include('app.goods.urls')),
# 登记了绝对路径后，URL文件位置可简写
# path('', include('common.urls')),
# ('polls.urls', "polls")

online_Book/app/cart/models.py
from django.db import models

# Create your models here.

online_Book/app/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from utils.mixin import LoginRequiredMixin
from django.http import JsonResponse
from django_redis import get_redis_connection
from goods.models import GoodsSKU


# Create your views here.
# 添加商品到购物车:
# 1）请求方式，采用ajax post
# 如果涉及到数据的修改(新增，更新，删除), 采用post
# 如果只涉及到数据的获取，采用get
# 2) 传递参数: 商品id(sku_id) 商品数量(count)

# /cart/add
class CartAddView(LoginRequiredMixin, View):
    """购物车记录的添加"""

    def post(self, request):
        """购物车记录添加"""
        # 获取用户实体
        user = request.user
        # if not user.is_authenticated:
        #     # 用户未登录
        #     return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接受数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整哦'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目不对哦'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在哦'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 尝试获取sku_id的值 -> hget_cart_key 属性
        # 如果sku_id在hash中不存在，hget 返回 None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品没货了
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置hash中sku_id对应的值
        # hset->如果sku_id已经存在，更新数据， 如果sku_id不存在，添加数据
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    """购物车页面显示"""

    def get(self, request):
        """显示"""

        # 获取登录的用户
        user = request.user

        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # {' 商品id '：商品数量}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_count = 0
        total_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            # 动态给sku对象增加一个属性amount，保存商品的小计
            sku.amount = amount
            # 动态给sku对象增加一个属性count，保存购物车中商品的数量
            sku.count = int(count)
            print(count)
            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus
        }

        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传输的参数：商品id（sku_id) 更新的商品数量
# /cart/update
class CartUpdateView(View):
    """购物车记录更新"""

    def post(self, request):
        """购物车记录更新"""
        # 获取登录的用户
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接受数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整哦，请补充完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目不对哦，请重新输入'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在哦，请重新输入'})

        # 业务处理：更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品没有货了，稍后再来吧'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'errmsg': '更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数
# cart/delete
class CartDeleteView(View):
    """购物车记录删除"""
    def post(self, request):
        # 获取登录的用户
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接受参数
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '数据不完整哦，请补充完整'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在哦，请重新输入'})

        # 业务处理：更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

online_Book/templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题内容块 #}
    <title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
{#	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>#}
{#	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>#}
{#    类似于java抽象类的父类，写好基类之后，写新的页面直接重写即可    #}
    {#  网页顶部引入文件块  #}
    {% block topfiles %} {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到研途无忧!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{user.username}}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">登出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a> {# 默认跳到第一页 #}
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con%}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
			    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body%}
{% endblock %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2021 研途无忧网上书城 All Rights Reserved</p>
		<p>电话：0731-****888    湘ICP备*******8号</p>
	</div>
    {# 网页底部元素块 #}
    {% block bottom %}
    {% endblock bottom %}
    {#  网页底部引入文件块  #}
    {% block bottomfiles %}
    {% endblock bottomfiles %}
</body>
</html>

online_Book/templates/base_no_cart.html
{# 购物车 提交订单 - 父模板#}
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">
            |&nbsp;&nbsp;&nbsp;&nbsp;
            {% block page_title %}
            {% endblock page_title %}
        </div>
		<div class="search_con fr">
            <form method="get" action="/search">
			    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

online_Book/templates/base_user_center.html
{# 用户中心三页面 #}
{% extends 'base_no_cart.html' %}
{% block title %} 研途无忧-用户中心 {% endblock title %}
{% block page_title %} 用户中心 {% endblock page_title %}
{% block body %}
    	<div class="main_con clearfix">
            <div class="left_menu_con clearfix">
                <h3>用户中心</h3>
                <ul>
                    <li><a href="{% url 'user:user' %}"
                           {% if page == 'user' %}
                           class="active"
                           {% endif %}>· 个人信息</a></li>

                    <li><a href="{% url 'user:order' 1 %}"
                            {% if page == 'order' %}
                           class="active"
                           {% endif %}>· 全部订单</a></li>

                    <li><a href="{% url 'user:address' %}"
                            {% if page == 'address' %}
                           class="active"
                           {% endif %}>· 收货地址</a></li>
                </ul>
            </div>
            {# 用户中心右侧内容块 #}
            {% block right_content %}

            {% endblock right_content %}
        </div>
{% endblock body %}

online_Book/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}研途无忧-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机研书</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
    {#种类信息的使用#}
        <ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
{#                forloop.counter从0开始往后边数#}
            {% endfor %}
		</ul>
    {#轮播商品的使用#}
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
    {#广告页面的使用#}
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>
    {#种类信息的使用#}
    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

online_Book/templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %} 研途无忧-商品列表 {% endblock title %}


{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{type.name}}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
						    <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.iamge.url }}"></a>
						    <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						    <div class="prize">￥{{ sku.price }}</div>
					    </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
{#				<a href="{% url 'goods:list' type.id 1 %}?sort={{ sort }}" class="active">默认</a>#}
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %} class="active" {% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %} class="active" {% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %} class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in skus_page %}
                <li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
{#						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>#}
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}

			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				    <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

                {% if skus_page.has_next %}
				    <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>

		</div>
	</div>

{% endblock main_content %}

online_Book/templates/login.html
{#<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">#}
{#<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">#}
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} 研途无忧-登录 {% endblock title %}
{% block header_con %}  {% endblock header_con %}
{% block search_bar %}  {% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png'%}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">一站购齐  ·  轻松备考</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {# 不设置表单的action值，提交表单时，会向浏览器地址栏中的地址提交数据 #}
					<form method="post" action="">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

online_Book/templates/static_base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题内容块 #}
    <title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
{#	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>#}
{#	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>#}
{#    类似于java抽象类的父类，写好基类之后，写新的页面直接重写即可    #}
    {#  网页顶部引入文件块  #}
    {% block topfiles %} {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到研途无忧!</div>
			<div class="fr">

				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con%}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body%}

{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2021 研途无忧网上书城 All Rights Reserved</p>
		<p>电话：0731-****888    湘ICP备*******8号</p>
	</div>
    {# 网页底部元素块 #}
    {% block bottom %}
    {% endblock bottom %}
    {#  网页底部引入文件块  #}
    {% block bottomfiles %}
    {% endblock bottomfiles %}
</body>
</html>